name: web_simple
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0-116.0.dev <3.0.0'


dependencies:
  path: ^1.8.0
  args: ^1.6.0
  shelf: ^0.7.5
  shelf_static: ^0.2.8


dev_dependencies:
  lints: ^1.0.0
  build_runner: '>=1.6.2 <2.0.0'
  build_web_compilers: '>=2.6.1 <3.0.0'
  pedantic: ^1.9.0
